### ISSUE TITLE
Get chain details from chain registry

### ISSUE THREAD

**Issue by CyberHoward** [Abstract-OS/BOOT#2]
Add a daemon constructor that fetches the chain registry using https://docs.rs/chain-registry/0.1.0/chain_registry/index.html

**Comment by CyberHoward** [comment]
https://github.com/CronCats/cosmos-chain-registry

**Comment by PFC-developer** [comment]
https://github.com/CronCats/cosmos-chain-registry is AGPL3
https://github.com/informalsystems/hermes/blob/master/crates/chain-registry/Cargo.toml is ASL2

**Comment by CyberHoward** [comment]
Yes I mistakingly referenced the wrong repo. I have ly doubts about the chain-registry endpoint reliability tho. In my experience it's really bad...

**Comment by PFC-developer** [comment]
maybe a cargo job that would fetch, or potentially it could be fed in a json file from there? 
I usually like to use that file as a 'base' and then extend it with testnets & private RPC endpoints I have internally
